version: '3.8'
services:
  platform:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"